INSERT INTO F1.Driver (`id`, `name`, `age`, `country`, `team`, `team_id`)
VALUE ('1', 'Max Verstappen', '25', 'NED', 'Red Bull Racing Honda RBPT', '1'),
('2', 'Sergio Perez', '25', 'MEX', 'Red Bull Racing Honda RBPT', '1'),
('3', 'Fernando Alonso', '25', 'ESP', 'Aston Martin Aramco Mercedes', '2'),
('4', 'Carlos Sainz', '25', 'ESP', 'Ferrari', '4'),
('5', 'Lewis Hamilton', '25', 'GBR', 'Mercedes', '3'),
('6', 'George Russell', '25', 'GBR', 'Mercedes', '3'),
('7', 'Lance Stroll', '25', 'CAN', 'Aston Martin Aramco Mercedes', '2'),
('8', 'Charles Leclerc', '25', 'MON', 'Ferrari', '4'),
('9', 'Valtteri Bottas', '25', 'FIN', 'Alfa Romeo Ferrari', '6'),
('10', 'Esteban Ocon', '25', 'FRA', 'Alpine Renault', '5'),
('11', 'Pierre Gasly', '25', 'FRA', 'Alpine Renault', '5'),
('12', 'Kevin Magnussen', '25', 'DEN', 'Haas Ferrari', '7'),
('13', 'Alexander Albon', '25', 'THA', 'Williams Mercedes', '8'),
('14', 'Yuki Tsunoda', '25', 'JPN', 'AlphaTauri Honda RBPT', '9'),
('15', 'Nico Hulkenberg', '25', 'GER', 'Haas Ferrari', '7'),
('16', 'Logan Sargeant', '25', 'USA', 'Williams Mercedes', '8'),
('17', 'Zhou Guanyu', '25', 'CHN', 'Alfa Romeo Ferrari', '6'),
('18', 'Nyck De Vries', '25', 'NED', 'AlphaTauri Honda RBPT', '9'),
('19', 'Oscar Piastri', '25', 'AUS', 'McLaren Mercedes', '10'),
('20', 'Lando Norris', '25', 'GBR', 'McLaren Mercedes', '10');